---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
  namespace: keda
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: keda-operator